# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20171017_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='tweet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet'),
        ),
    ]
